### ISSUE TITLE
Remove code duplication in usage instructions

### ISSUE THREAD

**Issue by gonzalo-bulnes** [gonzalo-bulnes/dice#4]
The program [welcome message and instructions](https://github.com/gonzalo-bulnes/dice/blob/v1.0.0-alpha/src/main.rs#L8-L17) make extensive use of the `println!` macro, because they run across multiple lines, and long lines are difficult to read in the code as well.

A [raw string litteral](http://stackoverflow.com/questions/26611664/ddg#26621611) could be used instead, that would:

- keep the message readable in the code
- keep the message formatting unchanged in the program output
- require only one `println!` : )

**Note**: I'd like to [add some tests](https://github.com/gonzalo-bulnes/dice/issues/3) around this to make the refactoring easier, but I'll be more than happy to accept a contribution based on manual testing if I haven't added them when you pick it up!

**Comment by Bassetts** [comment]
I'd like to pick this up please 🙂
